steps:
- name: 'node:10.10.0'
  entrypoint: yarn
- name: 'node:10.10.0'
  entrypoint: yarn
  args: ['build']
steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: gsutil
  args: ['rsync', '-m', '-d', '-r', 'build/', 'gs://com-howiwish']
